---
apiVersion: v1
kind: Service
metadata:
  name: countrycode
  labels:
    app: countrycode
    tier: service
spec:
  selector:
    app: countrycode
    tier: backend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: countrycode
  labels:
    app: countrycode
    tier: backend
spec:
  replicas: 4
  selector:
    matchLabels:
      app: countrycode
      tier: backend
  template:
    metadata:
      labels:
        app: countrycode
        tier: backend
    spec:
      containers:
      - name: countrycode
        image: gcr.io/ops-edmund-ochieng/github-ochienged-countrycode:v1.0.2
        ports:
        - containerPort: 8080
        securityContext:
          runAsNonRoot: true
          readOnlyRootFilesystem: true
        volumeMounts:
          - name: tmp
            mountPath: /tmp
      volumes:
        - name: tmp
          emptyDir: {}
