---
apiVersion: v1
kind: Service
metadata:
  name: trivia
  labels:
    app: nginx
    tier: service
spec:
  selector:
    app: nginx
    tier: proxy
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  type: LoadBalancer
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: proxy
  namespace: default
data:
  proxy.conf: |
    server {
        listen       80;
        server_name  localhost;

        location / {
            proxy_pass  http://worldtrivia;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

    }
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
    tier: proxy
  name: nginx
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
      tier: proxy
  template:
    metadata:
      labels:
        app: nginx
        tier: proxy
    spec:
      containers:
      - image: nginx:latest
        imagePullPolicy: Always
        name: nginx
        resources: {}
        securityContext:
          readOnlyRootFilesystem: true
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 20
          periodSeconds: 5 
        volumeMounts:
          - name: proxy-config
            mountPath: /etc/nginx/conf.d
          - name: nginx-run
            mountPath: /var/run
          - name: nginx-cache
            mountPath: /var/cache/nginx
      volumes:
        - name: proxy-config
          configMap:
            name: proxy
        - name: nginx-run
          emptyDir: {}
        - name: nginx-cache
          emptyDir: {}
